frase = str(input('escreva uma palavra aqui: ')).strip()
new_frase = list(frase)
#new_frase.extend([new_frase.pop(), new_frase.pop()])
#new_frase.insert(1, new_frase.pop(2))
print(frase)
print(new_frase)
#new_frase.remove('g')
for c in range(5):
    new_frase.pop()
for c in  range(2):
    new_frase.extend('s')
new_frase.insert(len(new_frase), 'o')
#new_frase.insert(2, 'v')
#new_frase.insert(2, 'v')
#new_frase.insert(4, 'orvalhos')
#new_frase.extend('s')
nova_frase = ' '.join(new_frase)
print(new_frase)
print(nova_frase)